### ISSUE TITLE
Conflict with `dbt-utils` package due to this repo's packages.yml

### ISSUE THREAD

**Issue by ilmari-aalto** [calogica/dbt-date#8]
I'm trying out the new `dbt-expectations` package which installs `dbt-date` via its `packages.yml`.
Now `dbt-date` installs `dbt-utils` via its `packages.yml`.

But we already have a separate entry for the package `dbt-utils` in our project `packages.yml`, like this:
```yaml
packages:
  - git: "https://github.com/fishtown-analytics/dbt-utils.git"
    revision: 0.6.2
  - git: "https://github.com/calogica/dbt-expectations.git"
    revision: 0.2.0
```

Having `dbt-utils` imported twice causes an error when running `dbt deps`: 
```
Running with dbt=0.18.1
Encountered an error:
Found duplicate project "dbt_utils". This occurs when a dependency has the same project name as some other dependency.
```

The obvious solution is to remove the `dbt-utils` entry from our project `packages.yml`. But I quite like having it explicitly imported, and not via a dependency of a dependency which is not very obvious, if you see what I mean.

Do you think that there's anything to be done from the point of view of your package `dbt-date`?
Or perhaps we should open an issue in the main `dbt` repository for better resolution of package dependencies so that this type of error would not present itself? I.e. so that dbt would figure out that in fact it's the same package and there's not conflict.

Happy to chat over dbt Slack or comment in this issue!
