### ISSUE TITLE
Convert_Timezone is converting in reverse

### ISSUE THREAD

**Issue by Lunin-Marketing** [calogica/dbt-date#85]
## Issue
When using the `convert_timezone` utility, my datetime are converting in reverse (example below). 

## Example
I have a date/time field (datatype is `timestamptz`), `created_date`.   
This field has a value of `2022-02-02T02:22:55+00:00`   
When I run: `{{ dbt_date.convert_timezone("created_date", "America/Los_Angeles") }} As create_date` I get `2022-02-02T10:22:55`, whereas I would expect to get `2022-02-01T18:22:55`.    

## Details
1. Database: `postgres` ran through Amazon AWS RDS DB
1. dbt version: `1.2`
1. dbt_date version: `0.6.1`
1. Package.yml    

```
packages:
  - package: dbt-labs/dbt_external_tables
    version: 0.8.0
  - package: dbt-labs/dbt_utils
    version: 0.9.2
  - package: calogica/dbt_date
    version: 0.6.1
```
